// AboutPage 의 스타일 정의 (원래 AboutPage.jsx 안에 있던 것)

// 색상 상수 — styles 와 컴포넌트 양쪽에서 쓰므로 export 한다
export const ORANGE = "#E86F00";
export const ORANGE_LIGHT = "#FEF0E0";
export const ORANGE_BORDER = "#f5b85a";

export const styles = {
  page: {
    width: 1000,
    margin: "0 auto",
    padding: "2.5rem 2rem",
    fontFamily: "'Pretendard', 'Apple SD Gothic Neo', sans-serif",
    boxSizing: "border-box",
  },
  section: {
    paddingBottom: "2.5rem",
    marginBottom: "2.5rem",
    borderBottom: "0.5px solid #ede8e2",
  },
  lastSection: {
    paddingBottom: 0,
    marginBottom: 0,
    borderBottom: "none",
  },
  label: {
    fontSize: 16,
    letterSpacing: "1.5px",
    textTransform: "uppercase",
    color: ORANGE,
    marginBottom: 10,
    fontWeight: 600,
  },
  title: {
    fontSize: 28,
    fontWeight: 400,
    color: "#1a1a1a",
    marginBottom: 10,
    fontFamily: "Georgia, 'Times New Roman', serif",
    letterSpacing: "-1px",
  },
  desc: {
    fontSize: 16,
    color: "#6b6258",
    lineHeight: 1.75,
    maxWidth: 800,
  },
  featGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(2, 1fr)",
    gap: 12,
    marginTop: 20,
  },
  featCard: {
    border: "0.5px solid #ede8e2",
    borderRadius: 12,
    padding: 18,
    display: "flex",
    gap: 14,
    alignItems: "flex-start",
  },
  featIcon: {
    width: 38,
    height: 38,
    borderRadius: 12,
    background: ORANGE_LIGHT,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
    color: ORANGE,
  },
  featTitle: {
    fontSize: 16,
    fontWeight: 600,
    color: "#1a1a1a",
    marginBottom: 5,
  },
  featDesc: {
    fontSize: 14,
    color: "#8a7e74",
    lineHeight: 1.65,
  },
  showcaseGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: 12,
    marginTop: 20,
  },
  showcaseCard: {
    border: "0.5px solid #ede8e2",
    borderRadius: 12,
    overflow: "hidden",
    background: "#fff",
  },
  showcaseInput: {
    background: "#f5f5f5",
    padding: "12px 16px",
    borderBottom: "0.5px solid #ede8e2",
  },
  showcaseInputBadge: {
    fontSize: 12,
    color: ORANGE,
    fontWeight: 600,
    letterSpacing: "0.5px",
    marginBottom: 6,
  },
  showcaseInputText: {
    fontSize: 15,
    color: "#6b6258",
    lineHeight: 1.55,
  },
  showcaseApplyBox: {
    display: "grid",
    gridTemplateColumns: "72px 1fr",
    gap: "6px 10px",
    fontSize: 14,
    color: "#6b6258",
    lineHeight: 1.55,
  },
  showcaseApplyLabel: {
    color: "#a09488",
    fontWeight: 600,
  },
  showcaseResult: { padding: "12px 16px" },
  showcaseResultBadge: {
    fontSize: 12,
    color: "#aaa",
    marginBottom: 8,
    letterSpacing: "0.5px",
  },
  caseChip: {
    display: "inline-block",
    padding: "4px 12px",
    margin: "2px 3px 2px 0",
    background: ORANGE_LIGHT,
    color: "#C44010",
    borderRadius: 12,
    fontSize: 14,
  },
  tipGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: 12,
    marginTop: 20,
  },
  tipCardGood: {
    background: "#f0faf5",
    border: "0.5px solid #9FE1CB",
    borderRadius: 12,
    padding: "16px 18px",
  },
  tipCardBad: {
    background: "#fef5f5",
    border: "0.5px solid #F7C1C1",
    borderRadius: 12,
    padding: "16px 18px",
  },
  tipBadgeGood: {
    display: "inline-block",
    fontSize: 13,
    fontWeight: 600,
    padding: "2px 10px",
    borderRadius: 2,
    background: "#9FE1CB",
    color: "#085041",
    marginBottom: 12,
    letterSpacing: "0.3px",
  },
  tipBadgeBad: {
    display: "inline-block",
    fontSize: 13,
    fontWeight: 600,
    padding: "2px 10px",
    borderRadius: 2,
    background: "#F7C1C1",
    color: "#791F1F",
    marginBottom: 12,
    letterSpacing: "0.3px",
  },
  tipItem: {
    fontSize: 15,
    color: "#6b6258",
    lineHeight: 1.65,
    marginBottom: 6,
  },
  faqCard: {
    border: "0.5px solid #ede8e2",
    borderRadius: 12,
    padding: "4px 20px",
    marginTop: 20,
  },
  faqItem: {
    padding: "16px 0",
    borderBottom: "0.5px solid #ede8e2",
  },
  faqItemLast: { padding: "16px 0" },

  faqQ: {
    fontSize: 16,
    fontWeight: 600,
    color: "#1a1a1a",
    marginBottom: 6,
  },
  faqA: {
    fontSize: 15,
    color: "#8a7e74",
    lineHeight: 1.65,
  },
  ctaBox: {
    background: "#ffffff",
    border: `0.5px solid #E86F00`,
    borderRadius: 12,
    padding: "24px 28px",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 16,
    flexWrap: "wrap",
  },
  ctaTitle: {
    fontSize: 16,
    fontWeight: 600,
    color: "#1a1a1a",
    marginBottom: 4,
  },
  btn: {
    padding: "11px 24px",
    background: ORANGE,
    color: "#fff",
    border: "none",
    borderRadius: 12,
    fontSize: 15,
    fontWeight: 600,
    cursor: "pointer",
    whiteSpace: "nowrap",
  },
};
