// CaseMap 의 스타일 정의 (원래 CaseMap.jsx 안에 있던 것)
export const styles = {
  wrapper: {
    fontFamily: "'Pretendard', 'Apple SD Gothic Neo', sans-serif",
    padding: "0.5rem 0",
  },
  header: {
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "space-between",
    marginBottom: "1rem",
  },
  headerLabel: {
    fontSize: 15,
    letterSpacing: "0.1em",
    textTransform: "uppercase",
    color: "#999",
    marginBottom: 2,
  },
  titleRow: {
    display: "flex",
    alignItems: "center",
    gap: 14,
  },
  headerTitle: {
    fontSize: 25,
    fontWeight: 600,
    color: "#1a1a1a",
    margin: 0,
  },
  viewToggle: {
    display: "flex",
    alignItems: "center",
    gap: 4,
    padding: 4,
    background: "#f5f5f5",
    border: "1px solid #e0e0e0",
    borderRadius: 999,
  },
  viewToggleBtn: {
    border: "none",
    background: "transparent",
    padding: "7px 14px",
    borderRadius: 999,
    fontSize: 13,
    fontWeight: 700,
    color: "#666",
    cursor: "pointer",
    fontFamily: "inherit",
  },
  viewToggleBtnActive: {
    border: "none",
    background: "#111827",
    padding: "7px 14px",
    borderRadius: 999,
    fontSize: 13,
    fontWeight: 800,
    color: "#fff",
    cursor: "pointer",
    fontFamily: "inherit",
    boxShadow: "0 2px 7px rgba(0,0,0,0.14)",
  },
  mapContainer: {
    position: "relative",
    background: "#fafafa",
    border: "0.5px solid #e0e0e0",
    borderRadius: 2,
    overflow: "hidden",
    marginBottom: "1rem",
    minHeight: 430,
  },
  emptyText: {
    position: "absolute",
    top: "50%",
    left: "50%",
    transform: "translate(-50%, -50%)",
    fontSize: 14,
    color: "#999",
    zIndex: 10,
    pointerEvents: "none",
  },
  areaBadge: {
    position: "absolute",
    top: 14,
    right: 14,
    background: "rgba(255,255,255,0.94)",
    border: "0.5px solid #e0e0e0",
    borderRadius: 8,
    padding: "7px 10px",
    boxShadow: "0 2px 8px rgba(0,0,0,0.04)",
    zIndex: 20,
    pointerEvents: "none",
    maxWidth: 260,
  },
  areaLabel: {
    display: "block",
    fontSize: 11,
    color: "#aaa",
    marginBottom: 3,
    fontWeight: 700,
  },
  areaValue: {
    display: "block",
    fontSize: 14,
    color: "#333",
    fontWeight: 800,
  },
  areaDesc: {
    display: "block",
    fontSize: 11,
    color: "#999",
    lineHeight: 1.45,
    marginTop: 5,
  },
  tooltip: {
    position: "absolute",
    maxWidth: 320,
    background: "#fff",
    border: "0.5px solid #e0e0e0",
    borderRadius: 8,
    padding: "9px 12px",
    boxShadow: "0 4px 12px rgba(0,0,0,0.08)",
    pointerEvents: "none",
    zIndex: 30,
  },
  tooltipRank: {
    fontSize: 11,
    fontWeight: 800,
    color: "#E86F00",
    marginBottom: 4,
  },
  tooltipTitle: {
    fontSize: 13,
    fontWeight: 700,
    color: "#1a1a1a",
    lineHeight: 1.4,
    marginBottom: 3,
  },
  tooltipSub: {
    fontSize: 11,
    color: "#888",
    lineHeight: 1.5,
  },
  tooltipSimilarity: {
    fontSize: 11,
    color: "#E86F00",
    fontWeight: 700,
    marginTop: 4,
  },
  dynamicCaseListSection: {
    marginTop: 10,
    background: "#fff",
    border: "0.5px solid #e5e7eb",
    borderRadius: 8,
    overflow: "hidden",
  },
  dynamicCaseListToggle: {
    width: "100%",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    padding: "13px 16px",
    border: "none",
    background: "#fff",
    cursor: "pointer",
    fontFamily: "inherit",
  },
  dynamicCaseListToggleTitle: {
    fontSize: 14,
    fontWeight: 800,
    color: "#111827",
  },
  dynamicCaseListToggleText: {
    fontSize: 13,
    fontWeight: 800,
    color: "#E86F00",
  },
  dynamicCaseListPanel: {
    borderTop: "0.5px solid #eeeeee",
    padding: 14,
    background: "#fbfbfb",
  },
  dynamicCaseListHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    marginBottom: 12,
  },
  dynamicCaseListTitle: {
    fontSize: 14,
    fontWeight: 800,
    color: "#1f2937",
    margin: 0,
  },
  dynamicCaseListDesc: {
    fontSize: 12,
    color: "#9ca3af",
    margin: "4px 0 0",
  },
  dynamicCaseSortSelect: {
    height: 34,
    border: "1px solid #e5e7eb",
    borderRadius: 6,
    background: "#fff",
    padding: "0 10px",
    fontSize: 13,
    fontWeight: 700,
    color: "#374151",
    fontFamily: "inherit",
    outline: "none",
    cursor: "pointer",
  },
  dynamicCaseList: {
    display: "flex",
    flexDirection: "column",
    gap: 8,
    maxHeight: 360,
    overflowY: "auto",
  },
  dynamicCaseListItem: {
    width: "100%",
    textAlign: "left",
    border: "1px solid #eeeeee",
    background: "#fff",
    borderRadius: 8,
    padding: "11px 12px",
    cursor: "pointer",
    fontFamily: "inherit",
  },
  dynamicCaseListItemActive: {
    width: "100%",
    textAlign: "left",
    border: "1px solid #fed7aa",
    background: "#fff7ed",
    borderRadius: 8,
    padding: "11px 12px",
    cursor: "pointer",
    fontFamily: "inherit",
  },
  dynamicCaseListItemTop: {
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 10,
    marginBottom: 7,
  },
  dynamicCaseListItemTitleWrap: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    minWidth: 0,
  },
  dynamicCaseTopBadge: {
    flex: "0 0 auto",
    display: "inline-flex",
    alignItems: "center",
    height: 20,
    padding: "0 7px",
    borderRadius: 999,
    background: "#111827",
    color: "#fff",
    fontSize: 10.5,
    fontWeight: 900,
  },
  dynamicCaseListItemTitle: {
    fontSize: 13.5,
    fontWeight: 800,
    color: "#111827",
    lineHeight: 1.35,
  },
  dynamicCaseScore: {
    flex: "0 0 auto",
    fontSize: 12,
    fontWeight: 800,
    color: "#E86F00",
  },
  dynamicCaseListItemMeta: {
    display: "flex",
    flexWrap: "wrap",
    gap: "5px 8px",
    fontSize: 11.5,
    color: "#6b7280",
    marginBottom: 7,
  },
  dynamicCaseListItemSub: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
    fontSize: 11.5,
    color: "#9ca3af",
  },
  zoomControls: {
    position: "absolute",
    right: 14,
    bottom: 14,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 4,
    background: "#fff",
    border: "0.5px solid #e0e0e0",
    borderRadius: 8,
    padding: "6px 8px",
    boxShadow: "0 2px 8px rgba(0,0,0,0.04)",
    zIndex: 20,
  },
  zoomBtn: {
    width: 20,
    height: 20,
    border: "none",
    background: "transparent",
    color: "#444",
    fontSize: 15,
    cursor: "pointer",
    borderRadius: 4,
    lineHeight: 1,
  },
  zoomLevel: {
    fontSize: 11,
    color: "#aaa",
  },
  zoomHint: {
    position: "absolute",
    left: 14,
    bottom: 12,
    fontSize: 12,
    color: "#aaa",
    pointerEvents: "none",
  },
};
