// HistoryPage 의 스타일 정의 (원래 HistoryPage.jsx 안에 있던 것)
export const styles = {
  page: {
    maxWidth: 980,
    margin: "0 auto",
    padding: "2.5rem 2rem",
    fontFamily: "'Pretendard', 'Apple SD Gothic Neo', sans-serif",
  },
  pageHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: "2rem",
    paddingBottom: "1.25rem",
    borderBottom: "2px solid #E86F00",
  },
  pageTitle: {
    fontSize: 26,
    fontWeight: 800,
    color: "#1a1a1a",
    margin: 0,
    letterSpacing: "-0.02em",
  },
  count: {
    fontSize: 14,
    color: "#E86F00",
    fontWeight: 700,
    background: "#FEF0E9",
    padding: "4px 11px",
    borderRadius: 20,
  },
  backBtn: {
    fontSize: 14,
    color: "#777",
    background: "#fff",
    border: "1px solid #e8e8e8",
    borderRadius: 20,
    padding: "8px 14px",
    cursor: "pointer",
    fontFamily: "inherit",
  },
  historyToolbar: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 16,
  },
  tabGroup: {
    display: "flex",
    alignItems: "center",
    gap: 8,
  },
  tab: {
    padding: "9px 15px",
    borderRadius: 999,
    border: "1px solid #e7e7e7",
    background: "#fff",
    color: "#777",
    fontSize: 13,
    fontWeight: 800,
    cursor: "pointer",
    fontFamily: "inherit",
  },
  tabActive: {
    padding: "9px 15px",
    borderRadius: 999,
    border: "1px solid #fed7aa",
    background: "#fff7ed",
    color: "#E86F00",
    fontSize: 13,
    fontWeight: 900,
    cursor: "pointer",
    fontFamily: "inherit",
  },
  tabCount: {
    marginLeft: 4,
    fontSize: 12,
    fontWeight: 900,
  },
  clearBtn: {
    fontSize: 13,
    color: "#999",
    background: "none",
    border: "none",
    cursor: "pointer",
    fontFamily: "inherit",
  },
  empty: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: 12,
    padding: "6rem 2rem",
    border: "1px dashed #e5e5e5",
    borderRadius: 16,
    background: "#fff",
  },
  emptySmall: {
    padding: "4rem 2rem",
    border: "1px dashed #e5e5e5",
    borderRadius: 16,
    background: "#fff",
    textAlign: "center",
  },
  emptyText: {
    fontSize: 17,
    fontWeight: 700,
    color: "#777",
    margin: 0,
    textAlign: "center",
  },
  emptyTextSmall: {
    fontSize: 15,
    fontWeight: 700,
    color: "#999",
    margin: 0,
  },
  emptySubText: {
    fontSize: 14,
    color: "#aaa",
    textAlign: "center",
    lineHeight: 1.6,
    margin: 0,
  },
  goSearchBtn: {
    marginTop: 8,
    padding: "11px 22px",
    fontSize: 14,
    fontWeight: 700,
    color: "#fff",
    background: "#E86F00",
    border: "none",
    borderRadius: 4,
    cursor: "pointer",
    fontFamily: "inherit",
  },
  searchGroupList: {
    display: "flex",
    flexDirection: "column",
    gap: 16,
  },
  searchGroupCard: {
    background: "#fff",
    border: "1px solid #e8e8e8",
    borderRadius: 14,
    padding: "1.25rem 1.45rem",
    boxShadow: "0 3px 12px rgba(0,0,0,0.03)",
  },
  searchGroupHeader: {
    display: "flex",
    justifyContent: "space-between",
    gap: 16,
    paddingBottom: 16,
    borderBottom: "1px solid #f0f0f0",
  },
  searchGroupLabel: {
    fontSize: 12,
    color: "#E86F00",
    fontWeight: 900,
    margin: "0 0 8px",
  },
  searchGroupTitle: {
    fontSize: 18,
    fontWeight: 900,
    color: "#111",
    lineHeight: 1.45,
    letterSpacing: "-0.03em",
    margin: 0,
    wordBreak: "keep-all",
  },
  searchGroupDate: {
    fontSize: 12,
    color: "#aaa",
    flexShrink: 0,
    marginTop: 4,
  },
  searchCaseList: {
    display: "flex",
    flexDirection: "column",
  },
  searchCaseRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 16,
    padding: "16px 0",
    borderBottom: "1px solid #f5f5f5",
    cursor: "pointer",
  },
  searchCaseMain: {
    flex: 1,
    minWidth: 0,
  },
  searchCaseTitleLine: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    minWidth: 0,
  },
  searchCaseTitle: {
    fontSize: 15,
    fontWeight: 900,
    color: "#111",
    lineHeight: 1.45,
    margin: 0,
    letterSpacing: "-0.02em",
    wordBreak: "keep-all",
  },
  searchCaseMeta: {
    fontSize: 13,
    color: "#aaa",
    margin: "8px 0 0 0",
  },
  searchCaseRight: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    flexShrink: 0,
  },
  sourceBadge: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "6px 10px",
    borderRadius: 4,
    fontSize: 12,
    fontWeight: 900,
    whiteSpace: "nowrap",
  },
  sourceBadgeSearch: {
    background: "#FEF0E9",
    color: "#E86F00",
  },
  sourceBadgePopular: {
    background: "#fff7ed",
    color: "#C45E00",
  },
  sourceBadgeDefault: {
    background: "#f3f3f3",
    color: "#666",
  },
  rowSummaryBtn: {
    padding: "8px 12px",
    border: "1px solid #ddd",
    background: "#fff",
    borderRadius: 4,
    fontSize: 13,
    fontWeight: 900,
    cursor: "pointer",
    fontFamily: "inherit",
  },
  rowArticleBtn: {
    padding: "8px 12px",
    border: "none",
    background: "#FEF0E9",
    color: "#E86F00",
    borderRadius: 4,
    fontSize: 13,
    fontWeight: 900,
    cursor: "pointer",
    fontFamily: "inherit",
  },
  rowRemoveBtn: {
    width: 34,
    height: 34,
    borderRadius: "50%",
    border: "none",
    background: "#f7f7f7",
    color: "#aaa",
    fontSize: 14,
    cursor: "pointer",
  },
  grid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(360px, 1fr))",
    gap: 18,
  },
  card: {
    background: "#fff",
    border: "1px solid #e8e8e8",
    borderRadius: 14,
    padding: "1.3rem",
    display: "flex",
    flexDirection: "column",
    gap: 12,
    boxShadow: "0 3px 12px rgba(0,0,0,0.03)",
    cursor: "pointer",
  },
  cardTop: {
    display: "flex",
    alignItems: "flex-start",
    gap: 12,
  },
  cardTitle: {
    fontSize: 16,
    fontWeight: 800,
    color: "#1a1a1a",
    lineHeight: 1.45,
    margin: "0 0 7px",
    letterSpacing: "-0.02em",
  },
  cardMeta: {
    fontSize: 13,
    color: "#999",
    margin: 0,
  },
  removeBtn: {
    background: "#f7f7f7",
    border: "none",
    borderRadius: "50%",
    cursor: "pointer",
    width: 34,
    height: 34,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
    fontSize: 14,
    color: "#aaa",
  },
  cardInfoRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    marginTop: 2,
  },
  tags: {
    display: "flex",
    flexWrap: "wrap",
    gap: 6,
    minWidth: 0,
  },
  tag: {
    padding: "5px 10px",
    fontSize: 12,
    color: "#666",
    background: "#f3f3f3",
    borderRadius: 4,
    fontWeight: 600,
  },
  viewedAt: {
    fontSize: 12,
    color: "#bbb",
    whiteSpace: "nowrap",
    flexShrink: 0,
  },
  cardBottom: {
    display: "flex",
    alignItems: "center",
    justifyContent: "flex-start",
    gap: 8,
    marginTop: 4,
  },
  summaryBtn: {
    fontSize: 13,
    fontWeight: 800,
    color: "#333",
    background: "#fff",
    border: "1px solid #d9d9d9",
    borderRadius: 4,
    padding: "8px 13px",
    cursor: "pointer",
    fontFamily: "inherit",
  },
  articleBtn: {
    fontSize: 13,
    fontWeight: 800,
    color: "#E86F00",
    background: "#FEF0E9",
    border: "none",
    borderRadius: 4,
    padding: "8px 13px",
    cursor: "pointer",
    fontFamily: "inherit",
  },
  detailPanel: {
    position: "fixed",
    top: 72,
    right: 0,
    bottom: 0,
    width: 390,
    background: "#fff",
    borderLeft: "1px solid #e8e8e8",
    boxShadow: "-12px 0 30px rgba(0,0,0,0.08)",
    zIndex: 900,
    display: "flex",
    flexDirection: "column",
  },
  detailHeader: {
    display: "flex",
    justifyContent: "space-between",
    gap: 16,
    padding: "24px 24px 18px",
    borderBottom: "1px solid #f0f0f0",
  },
  detailLabel: {
    fontSize: 13,
    fontWeight: 900,
    color: "#E86F00",
    margin: "0 0 8px",
  },
  detailTitle: {
    fontSize: 20,
    fontWeight: 900,
    color: "#111",
    lineHeight: 1.45,
    letterSpacing: "-0.03em",
    margin: "0 0 8px",
    wordBreak: "keep-all",
  },
  detailMeta: {
    fontSize: 13,
    color: "#999",
    margin: 0,
    lineHeight: 1.5,
  },
  detailCloseBtn: {
    width: 34,
    height: 34,
    borderRadius: "50%",
    border: "none",
    background: "#f7f7f7",
    color: "#999",
    cursor: "pointer",
    fontSize: 15,
    flexShrink: 0,
  },
  detailBody: {
    flex: 1,
    overflowY: "auto",
    padding: "20px 24px",
  },
  detailBadgeRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
    marginBottom: 16,
  },
  detailSourceBadge: {
    padding: "6px 10px",
    background: "#FEF0E9",
    color: "#E86F00",
    borderRadius: 4,
    fontSize: 12,
    fontWeight: 900,
  },
  detailViewedAt: {
    fontSize: 12,
    color: "#aaa",
  },
  detailSectionSoft: {
    background: "#fff7ed",
    border: "1px solid #fed7aa",
    borderRadius: 12,
    padding: "14px 15px",
    marginBottom: 18,
  },
  detailSection: {
    padding: "18px 0",
    borderTop: "1px solid #f0f0f0",
  },
  detailSectionLabel: {
    fontSize: 12,
    color: "#E86F00",
    fontWeight: 900,
    margin: "0 0 8px",
  },
  detailSectionTitle: {
    fontSize: 14,
    fontWeight: 900,
    color: "#111",
    margin: "0 0 10px",
  },
  detailQueryText: {
    fontSize: 14,
    color: "#333",
    fontWeight: 800,
    lineHeight: 1.6,
    margin: 0,
    wordBreak: "keep-all",
  },
  detailSearchDate: {
    fontSize: 12,
    color: "#b87839",
    margin: "8px 0 0",
  },
  detailParagraph: {
    fontSize: 14,
    color: "#333",
    lineHeight: 1.8,
    margin: 0,
    whiteSpace: "pre-line",
    wordBreak: "keep-all",
  },
  detailStrategyText: {
    fontSize: 14,
    color: "#333",
    lineHeight: 1.85,
    margin: 0,
    whiteSpace: "pre-line",
    wordBreak: "keep-all",
  },
  detailEmptyText: {
    fontSize: 13,
    color: "#999",
    lineHeight: 1.7,
    margin: 0,
    wordBreak: "keep-all",
  },
  detailFooter: {
    display: "flex",
    justifyContent: "flex-end",
    gap: 8,
    padding: "16px 20px",
    borderTop: "1px solid #f0f0f0",
    background: "#fafafa",
  },
  modalOverlay: {
    position: "fixed",
    top: 0, left: 0, right: 0, bottom: 0,
    background: "rgba(0,0,0,0.45)",
    zIndex: 1000,
  },
  modal: {
    position: "fixed",
    top: "50%",
    left: "50%",
    transform: "translate(-50%, -50%)",
    width: "min(620px, calc(100vw - 40px))",
    maxHeight: "78vh",
    background: "#fff",
    borderRadius: 16,
    zIndex: 1100,
    boxShadow: "0 18px 50px rgba(0,0,0,0.18)",
    overflow: "hidden",
    display: "flex",
    flexDirection: "column",
  },
  modalHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: 16,
    padding: "22px 24px 18px",
    borderBottom: "1px solid #f0f0f0",
  },
  modalLabel: {
    fontSize: 13,
    fontWeight: 800,
    color: "#E86F00",
    margin: "0 0 8px",
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: 800,
    color: "#1a1a1a",
    lineHeight: 1.45,
    margin: "0 0 8px",
    letterSpacing: "-0.03em",
  },
  modalMeta: {
    fontSize: 13,
    color: "#999",
    margin: 0,
  },
  modalCloseBtn: {
    width: 32,
    height: 32,
    borderRadius: "50%",
    border: "none",
    background: "#f7f7f7",
    color: "#999",
    cursor: "pointer",
    fontSize: 16,
    flexShrink: 0,
  },
  modalBody: {
    padding: "22px 24px",
    overflowY: "auto",
  },
  summaryParagraph: {
    fontSize: 15,
    color: "#333",
    lineHeight: 1.9,
    margin: "0 0 18px",
    letterSpacing: "-0.01em",
    wordBreak: "keep-all",
  },
  modalFooter: {
    display: "flex",
    justifyContent: "flex-end",
    gap: 8,
    padding: "16px 24px",
    borderTop: "1px solid #f0f0f0",
    background: "#fafafa",
  },
  modalSubBtn: {
    padding: "9px 16px",
    fontSize: 14,
    fontWeight: 700,
    color: "#666",
    background: "#fff",
    border: "1px solid #ddd",
    borderRadius: 4,
    cursor: "pointer",
    fontFamily: "inherit",
  },
  modalMainBtn: {
    padding: "9px 16px",
    fontSize: 14,
    fontWeight: 800,
    color: "#fff",
    background: "#E86F00",
    border: "none",
    borderRadius: 4,
    cursor: "pointer",
    fontFamily: "inherit",
  },
};
