// SearchPage 의 스타일 정의 (원래 SearchPage.jsx 안에 있던 것)
export const styles = {
  resultActionGroup: { display: "flex", alignItems: "center", gap: 8, flexWrap: "wrap", justifyContent: "flex-end" },
  personalStrategyActionBox: { width: "100%", padding: "0 0 12px", margin: "0 0 12px", borderBottom: "1px solid #f0f0f0", background: "transparent" },
  personalStrategyActionTitle: { margin: "0 0 4px", fontSize: 13, fontWeight: 900, color: "#E86F00" },
  personalStrategyActionDesc: { flex: 1, margin: 0, fontSize: 12.5, color: "#888", lineHeight: 1.45, wordBreak: "keep-all" },
  personalStrategyToast: { position: "fixed", right: 28, bottom: 92, zIndex: 2200, display: "flex", alignItems: "center", gap: 12, width: 320, padding: "14px 16px", background: "#fff", border: "1px solid #F7D8C6", borderLeft: "4px solid #E86F00", borderRadius: 12, boxShadow: "0 12px 32px rgba(0,0,0,0.14)" },
  personalStrategyToastIcon: { width: 28, height: 28, borderRadius: "50%", background: "#E86F00", color: "#fff", display: "flex", alignItems: "center", justifyContent: "center", fontSize: 15, fontWeight: 900, flexShrink: 0 },
  personalStrategyToastTitle: { margin: "0 0 3px", fontSize: 13, fontWeight: 900, color: "#1a1a1a" },
  personalStrategyToastText: { margin: 0, fontSize: 12.5, lineHeight: 1.45, color: "#666" },
  personalStrategyTopBtn: { width: "100%", minHeight: 44, padding: "0 16px", display: "flex", alignItems: "center", justifyContent: "center", gap: 8, fontSize: 14, fontWeight: 900, color: "#fff", background: "#E86F00", border: "1px solid #E86F00", borderRadius: 6, cursor: "pointer", fontFamily: "inherit", whiteSpace: "nowrap", boxShadow: "0 8px 18px rgba(232, 111, 0, 0.18)", transition: "all 0.2s ease" },
  personalStrategyTopBtnArrow: { fontSize: 16, fontWeight: 900, lineHeight: 1, transform: "translateY(-1px)" },
  personalModalOverlay: { position: "fixed", top: 0, left: 0, right: 0, bottom: 0, background: "rgba(0,0,0,0.48)", zIndex: 1200 },
  personalModal: { position: "fixed", top: "50%", left: "50%", transform: "translate(-50%, -50%)", width: "min(620px, calc(100vw - 40px))", maxHeight: "88vh", overflowY: "auto", background: "#fff", borderRadius: 16, zIndex: 1300, padding: 30, boxShadow: "0 18px 50px rgba(0,0,0,0.18)", boxSizing: "border-box" },
  personalModalHeader: { display: "flex", justifyContent: "space-between", alignItems: "flex-start", gap: 18, marginBottom: 18 },
  personalModalLabel: { margin: "0 0 6px", fontSize: 12, fontWeight: 900, color: "#E86F00", letterSpacing: "0.08em" },
  personalModalTitle: { margin: "0 0 8px", fontSize: 22, fontWeight: 900, color: "#1a1a1a" },
  personalModalDesc: { margin: 0, fontSize: 14, lineHeight: 1.65, color: "#666", wordBreak: "keep-all" },
  personalModalCloseBtn: { background: "rgba(232,111,0,0.1)", border: "none", borderRadius: "50%", width: 34, height: 34, color: "#E86F00", fontSize: 16, cursor: "pointer", flexShrink: 0 },
  personalExampleBox: { background: "#FEF0E9", border: "1px solid #F7D8C6", borderRadius: 10, padding: "13px 15px", marginBottom: 14 },
  personalExampleTitle: { margin: "0 0 6px", fontSize: 12, fontWeight: 900, color: "#E86F00" },
  personalExampleText: { margin: 0, fontSize: 13.5, lineHeight: 1.65, color: "#555", wordBreak: "keep-all" },
  personalTextarea: { width: "100%", minHeight: 150, padding: 15, border: "1px solid #e0e0e0", borderRadius: 10, resize: "vertical", fontSize: 14, lineHeight: 1.7, color: "#1a1a1a", fontFamily: "inherit", outline: "none", boxSizing: "border-box" },
  personalErrorText: { margin: "10px 0 0", fontSize: 13, fontWeight: 700, color: "#c0392b" },
  personalLoadingBox: { marginTop: 14, padding: "14px 15px", background: "linear-gradient(135deg, #FFF8F2 0%, #ffffff 100%)", border: "1px solid #F7D8C6", borderRadius: 12, boxShadow: "0 8px 22px rgba(232,111,0,0.08)" },
  personalLoadingTop: { display: "flex", alignItems: "center", gap: 12, marginBottom: 12 },
  personalLoadingSpinner: { width: 22, height: 22, borderRadius: "50%", border: "3px solid rgba(232,111,0,0.18)", borderTopColor: "#E86F00", animation: "personalStrategySpin 0.8s linear infinite", flexShrink: 0 },
  personalLoadingTitle: { margin: "0 0 4px", fontSize: 13, fontWeight: 900, color: "#1a1a1a", wordBreak: "keep-all" },
  personalLoadingStep: { margin: 0, fontSize: 12.5, lineHeight: 1.5, color: "#E86F00", fontWeight: 750, animation: "personalStrategyPulse 1.5s ease-in-out infinite", wordBreak: "keep-all" },
  personalLoadingProgressTrack: { position: "relative", height: 4, overflow: "hidden", background: "#F8E1D2", borderRadius: 999 },
  personalLoadingProgressBar: { position: "absolute", top: 0, left: 0, width: "34%", height: "100%", background: "linear-gradient(90deg, rgba(232,111,0,0.2), #E86F00, rgba(232,111,0,0.2))", borderRadius: 999, animation: "personalStrategyProgress 1.25s ease-in-out infinite" },
  personalSubmitLoadingText: { display: "inline-flex", alignItems: "center", justifyContent: "center", gap: 8 },
  personalBtnSpinner: { width: 13, height: 13, borderRadius: "50%", border: "2px solid rgba(255,255,255,0.38)", borderTopColor: "#fff", animation: "personalStrategySpin 0.75s linear infinite", flexShrink: 0 },
  personalModalNotice: { marginTop: 12, padding: "11px 13px", background: "#f8f8f8", border: "1px solid #eee", borderRadius: 8, fontSize: 12.5, color: "#777", lineHeight: 1.6, wordBreak: "keep-all" },
  personalModalFooter: { display: "flex", justifyContent: "flex-end", gap: 8, marginTop: 20 },
  personalCancelBtn: { padding: "10px 18px", fontSize: 13, color: "#666", background: "#fff", border: "1px solid #e0e0e0", borderRadius: 8, cursor: "pointer", fontFamily: "inherit" },
  personalSubmitBtn: { padding: "10px 18px", fontSize: 13, fontWeight: 800, color: "#fff", background: "#E86F00", border: "none", borderRadius: 8, fontFamily: "inherit" },
  personalStrategyBox: { background: "#fff", border: "1px solid #d9e7dc", borderLeft: "3px solid #4A8F57", borderRadius: 6, padding: "14px 15px", marginBottom: 12 },
  personalStrategyPreviewBox: { background: "#fff", border: "1px solid #d9e7dc", borderLeft: "3px solid #4A8F57", borderRadius: 6, padding: "14px 15px", marginBottom: 12 },
  personalStrategyPreviewText: { margin: "0 0 11px", fontSize: 13, lineHeight: 1.6, color: "#666", wordBreak: "keep-all" },
  personalStrategyOpenBtn: { width: "100%", padding: "10px 12px", fontSize: 13, fontWeight: 800, color: "#2F6F3A", background: "#F4FAF4", border: "1px solid #cfe4d2", borderRadius: 4, cursor: "pointer", fontFamily: "inherit" },
  personalStrategyModalLabel: { fontSize: 13, fontWeight: 800, color: "#2F6F3A", margin: "0 0 8px" },
  strategyModalBody: { padding: "22px 24px", overflowY: "auto" },
  strategyModalSection: { padding: "16px 0", borderBottom: "1px solid #f0f0f0" },
  strategyModalSectionTitle: { margin: "0 0 10px", fontSize: 14, fontWeight: 900, color: "#2F6F3A" },
  strategyModalParagraph: { margin: "0 0 10px", fontSize: 14.5, lineHeight: 1.85, color: "#333", letterSpacing: "-0.01em", wordBreak: "keep-all" },
  strategyActionLine: { margin: "0 0 8px", padding: "9px 11px", fontSize: 14, lineHeight: 1.65, color: "#333", background: "#F7FBF7", border: "1px solid #e2efe4", borderRadius: 8, wordBreak: "keep-all" },
  personalStrategyHeader: { display: "flex", alignItems: "center", justifyContent: "space-between", gap: 8, marginBottom: 9 },
  personalStrategyTitle: { margin: 0, fontSize: 13, fontWeight: 900, color: "#2F6F3A" },
  personalStrategyParagraph: { margin: "0 0 9px", fontSize: 13.5, lineHeight: 1.75, color: "#444", wordBreak: "keep-all" },
  personalStrategyBadge: { flexShrink: 0, padding: "3px 7px", fontSize: 11, fontWeight: 800, color: "#2F6F3A", background: "#EEF7EF", borderRadius: 999 },
  personalStrategyBadgeMuted: { flexShrink: 0, padding: "3px 7px", fontSize: 11, fontWeight: 800, color: "#777", background: "#f3f3f3", borderRadius: 999 },
  personalStrategyText: { margin: 0, fontSize: 13.5, lineHeight: 1.75, color: "#444", wordBreak: "keep-all" },
  personalStrategyGuide: { margin: "8px 0 0", fontSize: 12, color: "#777", lineHeight: 1.5 },
  personalStrategyEmptyBox: { background: "#fff", border: "1px dashed #dedede", borderRadius: 6, padding: "13px 14px", marginBottom: 12 },
  personalStrategyEmptyTitle: { margin: "0 0 7px", fontSize: 13, fontWeight: 800, color: "#777" },
  personalStrategyEmptyText: { margin: 0, fontSize: 13, lineHeight: 1.65, color: "#999", wordBreak: "keep-all",
    whiteSpace: "pre-line",
  },
  personalStrategyApplyBtn: { width: "100%", marginTop: 10, padding: "10px 12px", fontSize: 13, fontWeight: 800, color: "#fff", background: "#E86F00", border: "none", borderRadius: 12, cursor: "pointer", fontFamily: "inherit" },
  comparePersonalBox: { background: "#fff", border: "1px solid #d9e7dc", borderLeft: "3px solid #4A8F57", borderRadius: 6, padding: "12px 13px" },
  comparePersonalTitle: { margin: "0 0 7px", fontSize: 12, fontWeight: 900, color: "#2F6F3A" },
  comparePersonalText: { margin: 0, fontSize: 13, lineHeight: 1.7, color: "#444", wordBreak: "keep-all" },
  comparePersonalParagraph: { margin: "0 0 8px", fontSize: 13, lineHeight: 1.7, color: "#444", wordBreak: "keep-all" },
  comparePersonalPreviewText: { margin: "0 0 10px", fontSize: 12.5, lineHeight: 1.55, color: "#666", wordBreak: "keep-all" },
  comparePersonalEmptyBox: { background: "#fafafa", border: "1px dashed #e0e0e0", borderRadius: 6, padding: "12px 13px" },
  comparePersonalEmptyTitle: { margin: "0 0 7px", fontSize: 12, fontWeight: 900, color: "#999" },
  comparePersonalEmptyText: { margin: 0, fontSize: 13, lineHeight: 1.6, color: "#aaa", wordBreak: "keep-all" },
  comparePersonalEmptyParagraph: { margin: "0 0 8px", fontSize: 13, lineHeight: 1.6, color: "#aaa", wordBreak: "keep-all" },
  compareOverlay: { position: "fixed", top: 0, left: 0, right: 0, bottom: 0, background: "rgba(0,0,0,0.5)", zIndex: 500 },
  compareModal: { position: "fixed", top: "50%", left: "50%", transform: "translate(-50%, -50%)", width: "92%", maxWidth: 1180, maxHeight: "86vh", background: "#fff", borderRadius: 16, zIndex: 600, overflow: "hidden", display: "flex", flexDirection: "column", boxShadow: "0 18px 50px rgba(0,0,0,0.18)" },
  compareHeader: { background: "#f3f3f3", padding: "1.5rem 2rem", display: "flex", justifyContent: "space-between", alignItems: "flex-start", gap: 20 },
  compareTitle: { fontSize: 22, fontWeight: 800, color: "#1a1a1a", margin: "0 0 6px" },
  compareSubTitle: { fontSize: 15, color: "#666", margin: 0 },
  compareCloseBtn: { background: "rgba(232, 111, 0, 0.1)", border: "none", borderRadius: "50%", width: 34, height: 34, fontSize: 16, color: "#E86F00", cursor: "pointer", flexShrink: 0 },
  compareTableWrap: { overflowY: "auto", flex: 1 },
  compareTable: { width: "100%", borderCollapse: "collapse", tableLayout: "fixed" },
  compareHeaderRow: { borderBottom: "1px solid #e8e8e8" },
  compareLabelHead: { padding: "15px 16px", fontSize: 13, color: "#999", fontWeight: 700, textAlign: "left", background: "#fafafa", verticalAlign: "top" },
  compareCaseHead: { padding: "15px 16px", textAlign: "left", background: "#fafafa", borderLeft: "1px solid #e8e8e8", verticalAlign: "top" },
  compareCaseHeadInner: { display: "flex", alignItems: "flex-start", gap: 9, minWidth: 0 },
  compareCaseNum: { fontSize: 16, fontWeight: 900, color: "#E86F00", lineHeight: 1.4, flexShrink: 0 },
  compareCaseTitle: { fontSize: 13.5, fontWeight: 800, color: "#1a1a1a", lineHeight: 1.55, wordBreak: "keep-all", margin: 0 },
  compareCaseCompany: { fontSize: 12, color: "#999", fontWeight: 600, margin: "6px 0 0", lineHeight: 1.4 },
  compareRow: { borderBottom: "1px solid #f0f0f0" },
  compareLabelCell: { padding: "15px 16px", fontSize: 13, color: "#666", fontWeight: 700, background: "#fafafa", verticalAlign: "top" },
  compareValueCell: { padding: "15px 16px", fontSize: 13.5, color: "#1a1a1a", borderLeft: "1px solid #f0f0f0", verticalAlign: "top", lineHeight: 1.65, wordBreak: "keep-all" },
  compareReasonBox: { background: "#FFF6F0", border: "1px solid #F3D8C7", borderLeft: "3px solid #E86F00", borderRadius: 6, padding: "12px 13px" },
  compareReasonTitle: { fontSize: 12, fontWeight: 900, color: "#C45E00", margin: "0 0 7px" },
  compareReasonText: { fontSize: 13, color: "#555", lineHeight: 1.7, margin: 0, wordBreak: "keep-all" },
  compareReasonParagraph: { margin: "0 0 8px", fontSize: 13, color: "#555", lineHeight: 1.7, wordBreak: "keep-all" },
  compareSummaryBtn: { padding: "9px 13px", fontSize: 13, fontWeight: 800, color: "#E86F00", background: "#fff", border: "1px solid #E86F00", borderRadius: 4, cursor: "pointer", fontFamily: "inherit" },
  compareFooter: { padding: "1rem 2rem", borderTop: "1px solid #e8e8e8", display: "flex", justifyContent: "flex-end", gap: 8, background: "#fff" },
  compareFooterBtn: { padding: "10px 20px", fontSize: 13, color: "#666", background: "#fff", border: "1px solid #e0e0e0", borderRadius: 8, cursor: "pointer", fontFamily: "inherit" },
  compareExportBtn: { padding: "10px 20px", fontSize: 13, color: "#fff", background: "#E86F00", border: "1px solid #E86F00", borderRadius: 8, cursor: "pointer", fontFamily: "inherit", fontWeight: 800 },
  exportModalOverlay: { position: "fixed", top: 0, left: 0, right: 0, bottom: 0, background: "rgba(0,0,0,0.45)", zIndex: 800 },
  exportModal: { position: "fixed", top: "50%", left: "50%", transform: "translate(-50%, -50%)", width: "min(560px, calc(100vw - 40px))", background: "#fff", borderRadius: 16, zIndex: 900, boxShadow: "0 18px 50px rgba(0,0,0,0.22)", overflow: "hidden" },
  exportModalHeader: { padding: "24px 28px 18px", borderBottom: "1px solid #f0f0f0", display: "flex", justifyContent: "space-between", alignItems: "flex-start", gap: 16 },
  exportModalLabel: { margin: "0 0 6px", fontSize: 12, fontWeight: 900, color: "#E86F00", letterSpacing: "0.08em" },
  exportModalTitle: { margin: "0 0 8px", fontSize: 21, fontWeight: 900, color: "#1a1a1a" },
  exportModalDesc: { margin: 0, fontSize: 13, color: "#666", lineHeight: 1.6 },
  exportModalCloseBtn: { background: "rgba(232, 111, 0, 0.1)", border: "none", borderRadius: "50%", width: 32, height: 32, fontSize: 15, color: "#E86F00", cursor: "pointer", flexShrink: 0 },
  exportFixedItem: { margin: "18px 28px 10px", padding: "13px 14px", borderRadius: 10, background: "#fafafa", border: "1px solid #eee", display: "flex", justifyContent: "space-between", alignItems: "center" },
  exportFixedText: { fontSize: 14, fontWeight: 800, color: "#1a1a1a" },
  exportFixedBadge: { fontSize: 12, fontWeight: 800, color: "#E86F00", background: "#FEF0E9", padding: "5px 8px", borderRadius: 999 },
  exportOptionGrid: { padding: "8px 28px 24px", display: "grid", gridTemplateColumns: "1fr 1fr", gap: 10 },
  exportOptionItem: { width: "100%", padding: "12px 13px", border: "1px solid #eee", borderRadius: 10, background: "#fff", display: "flex", justifyContent: "space-between", alignItems: "center", cursor: "pointer", fontFamily: "inherit" },
  exportOptionText: { fontSize: 13.5, fontWeight: 700, color: "#333" },
  exportSwitch: { width: 42, height: 24, borderRadius: 999, padding: 3, display: "flex", alignItems: "center", transition: "all 0.2s", flexShrink: 0 },
  exportSwitchCircle: { width: 18, height: 18, borderRadius: "50%", background: "#fff", boxShadow: "0 1px 4px rgba(0,0,0,0.2)", transition: "transform 0.2s" },
  exportModalFooter: { padding: "16px 28px 24px", borderTop: "1px solid #f0f0f0", display: "flex", justifyContent: "flex-end", gap: 8 },
  exportCancelBtn: { padding: "10px 18px", fontSize: 13, color: "#666", background: "#fff", border: "1px solid #ddd", borderRadius: 8, cursor: "pointer", fontFamily: "inherit" },
  exportConfirmBtn: { padding: "10px 18px", fontSize: 13, color: "#fff", background: "#E86F00", border: "1px solid #E86F00", borderRadius: 8, cursor: "pointer", fontFamily: "inherit", fontWeight: 800 },
  topSearchLayout: { width: "min(1600px, calc(100vw - 96px))", margin: "0 auto", padding: "2.5rem 0 0", display: "grid", gridTemplateColumns: "minmax(840px, 1fr) 560px", gap: 24, alignItems: "start", boxSizing: "border-box" },
  searchMainCol: { minWidth: 0 },
  popularSideCol: { position: "sticky", top: 96, minWidth: 0, width: "100%" },
  popularRankBoard: { background: "transparent", border: "none", borderRadius: 0, padding: "16px 0", boxShadow: "none", display: "grid", gridTemplateColumns: "1.2fr 1px 0.8fr", gap: 14, minHeight: 520, alignItems: "start", width: "100%" },
  popularRankColumn: { minWidth: 0, display: "flex", flexDirection: "column", height: "100%" },
  popularRankDivider: { width: 1, background: "#f0f0f0", alignSelf: "stretch" },
  popularColumnHeader: { display: "flex", alignItems: "center", justifyContent: "space-between", gap: 10, marginBottom: 14 },
  popularCompactList: { display: "flex", flexDirection: "column", gap: 8, flex: 1, justifyContent: "space-between" },
  popularCaseCompactList: { display: "flex", flexDirection: "column", gap: 0, flex: 1, justifyContent: "stretch" },
  popularCompactItem: { width: "100%", display: "flex", alignItems: "flex-start", gap: 10, padding: "10px 8px", background: "#fff", border: "1px solid #f0f0f0", borderRadius: 8, cursor: "pointer", fontFamily: "inherit", textAlign: "left", transition: "all 0.2s" },
  popularCompactRank: { fontSize: 14, fontWeight: 800, color: "#E86F00", flexShrink: 0, minWidth: 14, lineHeight: 1.4 },
  popularCompactBody: { flex: 1, minWidth: 0, display: "flex", flexDirection: "column", gap: 3 },
  popularCompactMeta: { fontSize: 12, color: "#E86F00", fontWeight: 700, whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis" },
  popularCompactTitle: { fontSize: 13.5, fontWeight: 700, color: "#1a1a1a", lineHeight: 1.45, display: "-webkit-box", WebkitLineClamp: 2, WebkitBoxOrient: "vertical", overflow: "hidden" },
  popularCompactCompany: { fontSize: 12, color: "#999", whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis" },
  popularKeywordItem: { width: "100%", display: "flex", alignItems: "center", gap: 9, padding: "10px 8px", background: "#fff", border: "none", borderBottom: "1px solid #f0f0f0", borderRadius: 0, cursor: "pointer", fontFamily: "inherit", textAlign: "left", transition: "all 0.2s" },
  popularKeywordText: { flex: 1, minWidth: 0, fontSize: 12.5, fontWeight: 800, color: "#1a1a1a", lineHeight: 1.35, whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis" },
  popularKeywordCount: { minWidth: 22, height: 20, padding: "0 6px", borderRadius: 999, background: "#FEF0E9", color: "#E86F00", fontSize: 12, fontWeight: 800, display: "flex", alignItems: "center", justifyContent: "center" },
  page: { width: "100%", margin: "0 auto", padding: 0, fontFamily: "'Karrot Sans', 'Pretendard Variable', 'Pretendard', -apple-system, BlinkMacSystemFont, 'Apple SD Gothic Neo', 'Noto Sans KR', 'Segoe UI', sans-serif", boxSizing: "border-box" },
  splitRow: { display: "flex", gap: 16, alignItems: "flex-start", width: "min(1600px, calc(100vw - 96px))", margin: "0 auto", padding: "0 0 2rem", boxSizing: "border-box" },
  caseListCol: { width: 420, flexShrink: 0, borderRight: "1px solid #e0e0e0", paddingRight: 16 },
  mapCol: { flex: 1, minWidth: 0 },
  logoArea: { marginBottom: "2.5rem", textAlign: "center" },
  heroTitleWrap: { minHeight: 88, display: "flex", alignItems: "center", justifyContent: "center" },
  heroKeyword: { display: "inline-block", minWidth: 250, textAlign: "right", fontWeight: 850, lineHeight: 1.18, letterSpacing: "-0.045em", color: "#111827", animation: "heroKeywordSlide 2.3s ease-in-out both", willChange: "transform, opacity", verticalAlign: "baseline" },
  logoTitle: { margin: 0, fontSize: 34, fontWeight: 760, lineHeight: 1.32, letterSpacing: "-0.04em", color: "#1a1a1a", whiteSpace: "nowrap" },
  
  filterWrapper: { marginBottom: "1.5rem", background: "#fff", border: "1px solid #ede8e2", borderRadius: 12, padding: "20px 24px", boxShadow: "0 2px 10px rgba(0,0,0,0.02)", maxWidth: 800  },
  filterSection: { marginBottom: 16, paddingBottom: 16, borderBottom: "1px dashed #f0f0f0" },
  filterLabel: { fontSize: 15, fontWeight: 600, color: "#666", marginBottom: 10 },
  chipGroup: { display: "flex", flexWrap: "wrap", gap: 8 },
  chip: { padding: "7px 18px", fontSize: 13, fontWeight: 500, color: "#666", background: "#fff", border: "1px solid #e0e0e0", borderRadius: 20, cursor: "pointer", fontFamily: "inherit", transition: "all 0.2s" },
  chipActive: { padding: "7px 18px", fontSize: 13, fontWeight: 600, color: "#fff", background: "#E86F00", border: "1px solid #E86F00", borderRadius: 20, cursor: "pointer", fontFamily: "inherit", boxShadow: "0 2px 6px rgba(232, 111, 0, 0.2)" },
  chipNone: { padding: "7px 18px", fontSize: 13, fontWeight: 500, color: "#888", background: "#f9f9f9", border: "1px dashed #d0d0d0", borderRadius: 20, cursor: "pointer", fontFamily: "inherit", transition: "all 0.2s" },
  chipActiveNone: { padding: "7px 18px", fontSize: 13, fontWeight: 600, color: "#fff", background: "#666", border: "1px solid #666", borderRadius: 20, cursor: "pointer", fontFamily: "inherit", boxShadow: "0 2px 6px rgba(0, 0, 0, 0.15)" },

  textarea: { width: "100%", minHeight: 100, padding: "14px 16px", fontSize: 16, fontFamily: "inherit", color: "#1a1a1a", background: "#f5f5f5", borderRadius: 12, lineHeight: 1.6, outline: "none", boxSizing: "border-box", resize: "none", maxHeight: 180 },
  btnRow: { display: "flex", justifyContent: "flex-end", gap: 8, maxWidth: 848, margin: "12px auto 0.8rem" },
  btnClear: { padding: "8px 16px", fontSize: 15, color: "#666", background: "transparent", border: "1px solid #e0e0e0", borderRadius: 12, cursor: "pointer", fontFamily: "inherit" },
  btnSearch: { padding: "8px 20px", fontSize: 15, fontWeight: 500, color: "#fff", background: "#E86F00", border: "none", borderRadius: 12, fontFamily: "inherit" },
  exampleArea: { marginBottom: "1.5rem" },
  chipsLabel: { fontSize: 13, color: "#999", marginBottom: 6, textAlign: "center" },
  exampleChip: { padding: "4px 10px", fontSize: 13, color: "#E86F00", background: "#fef0e9", border: "none", borderRadius: 20, cursor: "pointer", fontFamily: "inherit", whiteSpace: "nowrap" },
  loadingRow: { display: "flex", alignItems: "center", gap: 8, padding: "1rem 0" },
  loadingText: { fontSize: 14, color: "#999" },
  dot: { width: 6, height: 6, borderRadius: "50%", background: "#E86F00", animation: "pulse 1.2s ease-in-out infinite" },
  errorText: { fontSize: 14, color: "#A32D2D", padding: "0.5rem 0" },
  inputPanel: { background: "#f0f0f0", border: "none", overflow: "hidden", boxSizing: "border-box", borderRadius: 12, maxWidth: 848 },
  exampleAreaInInput: { padding: "8px 14px 10px", background: "#fff", border: "none", boxSizing: "border-box" },
  loadingStatusArea: { minHeight: 44, display: "flex", alignItems: "center", justifyContent: "flex-start", padding: "0.2rem 0 1rem", marginTop: "-0.2rem" },
  loadingStatusText: { fontSize: 17, fontWeight: 600, color: "#E86F00", letterSpacing: "-0.01em" },
  loadingEllipsis: { display: "inline-block", width: 28, textAlign: "left" },

  popularBox: { background: "#fff", border: "1px solid #ede8e2", borderRadius: 12, padding: "18px", boxShadow: "0 2px 10px rgba(0,0,0,0.03)" },
  popularHeader: { display: "flex", justifyContent: "space-between", alignItems: "flex-start", marginBottom: 14 },
  popularEyebrow: { fontSize: 12, color: "#999", margin: 0, marginBottom: 4 },
  popularTitle: { fontSize: 20, fontWeight: 800, color: "#1a1a1a", margin: 0 },
  popularBadge: { fontSize: 12, fontWeight: 700, color: "#E86F00" },
  popularMessage: { fontSize: 14, color: "#777", lineHeight: 1.5, padding: "14px 0", margin: 0 },
  popularList: { display: "flex", flexDirection: "column", gap: 8 },
  popularItem: { display: "flex", gap: 12, padding: "12px 10px", borderRadius: 8, cursor: "pointer", border: "1px solid #f0f0f0", transition: "all 0.2s", background: "#fff" },
  popularRank: { fontSize: 14, fontWeight: 800, color: "#E86F00", flexShrink: 0, minWidth: 12 },
  popularMeta: { display: "flex", gap: 5, fontSize: 12, color: "#E86F00", fontWeight: 600, marginBottom: 4 },
  popularItemTitle: { fontSize: 14, fontWeight: 700, color: "#1a1a1a", lineHeight: 1.4, margin: 0, display: "-webkit-box", WebkitLineClamp: 2, WebkitBoxOrient: "vertical", overflow: "hidden" },
  popularCompany: { fontSize: 12, color: "#999", marginTop: 5 },

  recommendStatusBox: {
    background: "#FFF8F3",
    border: "1px solid #F3D8C7",
    borderLeft: "3px solid #E86F00",
    borderRadius: 6,
    padding: "12px 14px",
    marginBottom: 12,
  },

  recommendStatusTitle: {
    fontSize: 14,
    fontWeight: 800,
    color: "#C45E00",
    margin: "0 0 4px",
  },

  recommendStatusMessage: {
    fontSize: 13,
    color: "#666",
    lineHeight: 1.55,
    margin: 0,
  },

  infoBtn: { display: "flex", alignItems: "center", gap: 6, padding: "6px 12px", fontSize: 13, fontWeight: 600, color: "#E86F00", background: "#fef0e9", border: "none", borderRadius: 20, cursor: "pointer", transition: "background 0.2s" },
  card: { background: "#fff", border: "0.5px solid #fff", borderRadius: 12, padding: "1rem 1.25rem", marginBottom: 12 },
  cardLabel: { fontSize: 21, fontWeight: 700, letterSpacing: "0.1em", textTransform: "uppercase", color: "#1a1a1a", margin: 0, textAlign: "left" },
  problemSummary: { fontSize: 15, color: "#333", lineHeight: 1.7, marginBottom: 16 },
  divider: { border: "none", borderTop: "1px solid #f0f0f0", margin: "16px 0" },
  tagSectionLabel: { fontSize: 12, color: "#999", marginBottom: 8, fontWeight: 500 },
  tag: { padding: "4px 10px", fontSize: 13, borderRadius: 4, fontWeight: 500 },
  
  caseItem: { display: "flex", alignItems: "flex-start", gap: 14, padding: "14px 12px", border: "1px solid transparent", borderBottom: "1px solid #f0f0f0", borderRadius: 2, cursor: "pointer", transition: "all 0.2s" },
  caseRank: { width: 28, height: 28, display: "flex", alignItems: "center", justifyContent: "center", fontSize: 22, fontWeight: 700, flexShrink: 0, color: "#1a1a1a" },
  caseTitle: { fontSize: 15, fontWeight: 700, color: "#1a1a1a", marginBottom: 3 },
  caseMeta: { fontSize: 13, color: "#999" },
  caseTag: { padding: "4px 10px", fontSize: 13, color: "#555", background: "#f0f0f0", borderRadius: 2 },

  bottomBrowseSection: { width: 1000, margin: "0 auto 5rem", padding: "0 2rem", boxSizing: "border-box" },
  btnBrowseAll: { width: "100%", padding: "14px", fontSize: 16, fontWeight: 600, color: "#1a1a1a", background: "#f0f0f0", border: "none", borderRadius: 12, cursor: "pointer", transition: "all 0.2s" },
  allListWrapper: { background: "#fff", border: "1px solid #ede8e2", borderRadius: 12, padding: 24, marginTop: 10 },
  allListHeader: { display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 20 },
  allListTitle: { fontSize: 18, fontWeight: 700, color: "#1a1a1a", margin: 0 },
  btnCloseAll: { background: "none", border: "none", fontSize: 14, color: "#888", cursor: "pointer", fontWeight: 500 },
  allListGrid: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: "0 1px", borderTop: "1px solid #f0f0f0", background: "#f0f0f0" },
  archiveCard: { padding: "16px 12px", background: "#fff", borderBottom: "1px solid #f0f0f0", cursor: "pointer", transition: "all 0.2s" },
  archiveHeader: { display: "flex", justifyContent: "space-between", fontSize: 13, color: "#999", marginBottom: 6 },
  archiveIndustry: { fontSize: 14, fontWeight: 600, color: "#E86F00" },
  archiveDate: { fontSize: 14 },
  archiveTitle: { fontSize: 18, fontWeight: 900, color: "#1a1a1a", marginBottom: 4 },
  archiveCompany: { fontSize: 15, color: "#666", marginBottom: 8 },
  archiveSummary: { fontSize: 14, color: "#666", lineHeight: 1.5, display: "-webkit-box", WebkitLineClamp: 2, WebkitBoxOrient: "vertical", overflow: "hidden" },
  btnLoadMore: { padding: "12px 120px", fontSize: 14, fontWeight: 600, color: "#E86F00", background: "#fff", border: "1px solid #E86F00", borderRadius: 12, cursor: "pointer" },

  panel: { position: "fixed", top: 72, right: 0, width: 420, height: "calc(100vh - 72px)", background: "#fff", borderLeft: "1px solid #e0e0e0", boxShadow: "-4px 0 20px rgba(0,0,0,0.08)", zIndex: 200, padding: "2rem", boxSizing: "border-box", overflowY: "auto", display: "flex", flexDirection: "column" },
  panelHeader: { display: "flex", justifyContent: "space-between", alignItems: "flex-start", marginBottom: 8 },
  panelTitle: { fontSize: 20, fontWeight: 700, color: "#1a1a1a", lineHeight: 1.4, margin: 0, flex: 1 },
  panelMeta: { fontSize: 15, color: "#666", marginBottom: 16 },
  reasonBox: { background: "#FFF6F0", border: "1px solid #F3D8C7", borderLeft: "3px solid #E86F00", borderRadius: 6, padding: "14px 15px", marginBottom: 14 },
  summaryBox: { background: "#FFF9F5", border: "1px solid #F3D8C7", borderRadius: 6, padding: "13px 14px", marginBottom: 14 },
  reasonBoxWhite: { background: "#fff", border: "1px solid #eee", borderRadius: 6, padding: "14px", marginBottom: 14 },
  reasonTitle: { fontSize: 13, fontWeight: 900, color: "#C45E00", margin: "0 0 8px" },
  summaryBoxTitle: { fontSize: 13, fontWeight: 900, color: "#E86F00", margin: "0 0 6px" },
  reasonTitleDark: { fontSize: 13, fontWeight: 800, color: "#333", margin: "0 0 7px" },
  reasonItem: { fontSize: 14, color: "#555", lineHeight: 1.7, margin: 0, wordBreak: "keep-all" },
  insightTextGroup: { display: "flex", flexDirection: "column", gap: 8 },
  insightParagraph: { fontSize: 13.5, color: "#555", lineHeight: 1.75, margin: 0, wordBreak: "keep-all" },
  panelActionGroup: { display: "flex", flexDirection: "column", gap: 8, marginBottom: 14 },
  panelSummaryBtn: { width: "100%", padding: "11px 12px", fontSize: 13.5, fontWeight: 800, color: "#E86F00", background: "#fff", border: "1px solid #E86F00", borderRadius: 12, cursor: "pointer", fontFamily: "inherit" },
  panelLink: { width: "100%", padding: "12px", fontSize: 14, fontWeight: 600, color: "#E86F00", background: "#fff", border: "1px solid #E86F00", borderRadius: 12, cursor: "pointer", fontFamily: "inherit", display: "flex", alignItems: "center", justifyContent: "center", gap: 8, transition: "all 0.2s" },

  summaryPreviewHeader: { display: "flex", alignItems: "center", justifyContent: "space-between", gap: 14 },
  summaryPreviewText: { fontSize: 13, color: "#666", lineHeight: 1.5, margin: 0 },
  summaryOpenBtn: { flexShrink: 0, padding: "8px 11px", fontSize: 12.5, fontWeight: 800, color: "#E86F00", background: "#fff", border: "1px solid #E86F00", borderRadius: 4, cursor: "pointer", fontFamily: "inherit", whiteSpace: "nowrap" },

  caseSummaryModalOverlay: { position: "fixed", top: 0, left: 0, right: 0, bottom: 0, background: "rgba(0,0,0,0.45)", zIndex: 1000 },
  caseSummaryModal: { position: "fixed", top: "50%", left: "50%", transform: "translate(-50%, -50%)", width: "min(620px, calc(100vw - 40px))", maxHeight: "78vh", background: "#fff", borderRadius: 16, zIndex: 1100, boxShadow: "0 18px 50px rgba(0,0,0,0.18)", overflow: "hidden", display: "flex", flexDirection: "column" },
  caseSummaryModalHeader: { display: "flex", justifyContent: "space-between", alignItems: "flex-start", gap: 16, padding: "22px 24px 18px", borderBottom: "1px solid #f0f0f0" },
  caseSummaryModalLabel: { fontSize: 13, fontWeight: 800, color: "#E86F00", margin: "0 0 8px" },
  caseSummaryModalTitle: { fontSize: 20, fontWeight: 800, color: "#1a1a1a", lineHeight: 1.45, margin: "0 0 8px", letterSpacing: "-0.03em" },
  caseSummaryModalMeta: { fontSize: 13, color: "#999", margin: 0 },
  caseSummaryModalCloseBtn: { width: 32, height: 32, borderRadius: "50%", border: "none", background: "#f7f7f7", color: "#999", cursor: "pointer", fontSize: 16, flexShrink: 0 },
  caseSummaryModalBody: { padding: "22px 24px", overflowY: "auto" },
  caseSummaryParagraph: { fontSize: 15, color: "#333", lineHeight: 1.9, margin: "0 0 18px", letterSpacing: "-0.01em", wordBreak: "keep-all" },
  caseSummaryModalFooter: { display: "flex", justifyContent: "flex-end", gap: 8, padding: "16px 24px", borderTop: "1px solid #f0f0f0", background: "#fafafa" },
  caseSummaryModalSubBtn: { padding: "9px 16px", fontSize: 14, fontWeight: 700, color: "#666", background: "#fff", border: "1px solid #ddd", borderRadius: 4, cursor: "pointer", fontFamily: "inherit" },
  caseSummaryModalMainBtn: { padding: "9px 16px", fontSize: 14, fontWeight: 800, color: "#fff", background: "#E86F00", border: "none", borderRadius: 4, cursor: "pointer", fontFamily: "inherit" },

  bottomBar: { position: "fixed", bottom: 0, left: 0, right: 0, background: "#1a1a1a", color: "#fff", display: "flex", alignItems: "center", justifyContent: "space-between", padding: "14px 24px", zIndex: 300, boxShadow: "0 -4px 12px rgba(0,0,0,0.15)" },
  bottomBarText: { fontSize: 14, fontWeight: 500 },
  bottomBarBtnReset: { padding: "8px 16px", fontSize: 13, color: "#fff", background: "transparent", border: "1px solid #555", borderRadius: 12, cursor: "pointer" },
  bottomBarBtnOutline: { padding: "8px 16px", fontSize: 13, color: "#fff", background: "transparent", border: "1px solid #666", borderRadius: 12, cursor: "pointer" },
  bottomBarBtnFill: { padding: "8px 16px", fontSize: 13, color: "#1a1a1a", background: "#fff", border: "none", borderRadius: 12, cursor: "pointer" },

  fullScreenLoading: {
    position: "fixed",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    background: "rgba(255, 255, 255, 0.7)",
    backdropFilter: "blur(4px)",
    zIndex: 9999,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  loadingContent: {
    display: "flex",
    flexDirection: "column",
    padding: "36px 40px",
    background: "#fff",
    borderRadius: 2,
    boxShadow: "0 10px 40px rgba(0,0,0,0.1)",
    width: 520,
    maxWidth: "90%",
    boxSizing: "border-box"
  },
  progressHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-end",
    marginBottom: 16
  },
  loadingStatusTextCenter: {
    fontSize: 16,
    fontWeight: 700,
    color: "#1a1a1a",
    letterSpacing: "-0.01em",
    textAlign: "center",
  },
  progressPercent: {
    fontSize: 18,
    fontWeight: 800,
    color: "#E86F00"
  },
  progressBarContainer: {
    width: "100%",
    height: 8,
    background: "#f0f0f0",
    borderRadius: 4,
    overflow: "hidden"
  },
  progressBarFill: {
    height: "100%",
    background: "#E86F00",
    borderRadius: 4,
    transition: "width 0.4s ease-out"
  },

  loadingVisualWrap: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 22,
  },
  loadingVisualStage: {
    position: "relative",
    width: 196,
    height: 92,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  loadingBook: {
    position: "absolute",
    left: 26,
    top: 16,
    width: 58,
    height: 54,
    borderRadius: "4px 8px 8px 4px",
    background: "#fff",
    border: "1px solid #E7E7E7",
    transformStyle: "preserve-3d",
    perspective: 500,
    animation: "loadingBookPulse 2.2s ease-in-out infinite",
    overflow: "visible",
  },
  loadingBookCover: {
    position: "absolute",
    left: 0,
    top: 0,
    width: 29,
    height: "100%",
    borderRadius: "4px 2px 2px 4px",
    background: "#E86F00",
    color: "#fff",
    fontSize: 10,
    fontWeight: 800,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    letterSpacing: "0.02em",
  },
  loadingBookPageBack: {
    position: "absolute",
    left: 30,
    top: 7,
    width: 24,
    height: 38,
    borderRadius: "2px 6px 6px 2px",
    background: "linear-gradient(90deg, #fff 0%, #f4f4f4 100%)",
    border: "1px solid #eeeeee",
  },
  loadingBookPageFlip: {
    position: "absolute",
    left: 30,
    top: 7,
    width: 24,
    height: 38,
    borderRadius: "2px 6px 6px 2px",
    background: "#fff",
    border: "1px solid #eeeeee",
    transformOrigin: "left center",
    animation: "loadingPageFlip 1.65s ease-in-out infinite",
  },
  loadingCardsWrap: {
    position: "absolute",
    right: 22,
    top: 18,
    display: "flex",
    flexDirection: "column",
    gap: 6,
  },
  loadingMiniCard: {
    width: 74,
    height: 18,
    borderRadius: 5,
    background: "#FAFAFA",
    border: "1px solid #E8E8E8",
    display: "flex",
    alignItems: "center",
    gap: 5,
    padding: "0 7px",
    boxSizing: "border-box",
    animation: "loadingCardFloat 1.6s ease-in-out infinite",
  },
  loadingMiniCardLineLong: {
    display: "block",
    width: 34,
    height: 3,
    borderRadius: 3,
    background: "#D9D9D9",
  },
  loadingMiniCardLineShort: {
    display: "block",
    width: 16,
    height: 3,
    borderRadius: 3,
    background: "#E86F00",
    opacity: 0.55,
  },
  loadingMagnifier: {
    position: "absolute",
    left: 86,
    top: 35,
    width: 38,
    height: 38,
    animation: "loadingMagnifierScan 1.9s ease-in-out infinite",
  },
  loadingMagnifierCircle: {
    position: "absolute",
    left: 0,
    top: 0,
    width: 22,
    height: 22,
    borderRadius: "50%",
    border: "3px solid #1a1a1a",
    background: "rgba(255,255,255,0.55)",
  },
  loadingMagnifierHandle: {
    position: "absolute",
    left: 21,
    top: 23,
    width: 18,
    height: 3,
    borderRadius: 3,
    background: "#1a1a1a",
    transform: "rotate(45deg)",
    transformOrigin: "left center",
  },
  loadingStrategyStack: {
    position: "absolute",
    left: 86,
    top: 28,
    display: "flex",
    flexDirection: "column",
    gap: 5,
  },
  loadingStrategyChip: {
    width: 58,
    height: 20,
    borderRadius: 999,
    background: "#1a1a1a",
    color: "#fff",
    fontSize: 11,
    fontWeight: 700,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    animation: "loadingStrategySlide 1.5s ease-in-out infinite",
  },
  loadingMapDots: {
    position: "absolute",
    left: 92,
    top: 30,
    width: 58,
    height: 42,
  },
  loadingMapDot: {
    position: "absolute",
    width: 8,
    height: 8,
    borderRadius: "50%",
    background: "#E86F00",
    animation: "loadingMapPulse 1.4s ease-in-out infinite",
  },
  loadingVisualLabel: {
    margin: "2px 0 0",
    fontSize: 12,
    fontWeight: 700,
    color: "#888",
    letterSpacing: "0.02em",
  },

  invalidNoticeContent: {
    width: 520,
    maxWidth: "calc(100vw - 40px)",
    padding: "34px 38px",
    background: "#fff",
    borderRadius: 16,
    boxShadow: "0 10px 40px rgba(0,0,0,0.12)",
    border: "1px solid #f0f0f0",
    textAlign: "center",
    boxSizing: "border-box",
  },

  invalidNoticeIcon: {
    width: 34,
    height: 34,
    borderRadius: "50%",
    background: "#FEF0E9",
    color: "#E86F00",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 20,
    fontWeight: 900,
    margin: "0 auto 14px",
  },

  invalidNoticeTitle: {
    fontSize: 20,
    fontWeight: 800,
    color: "#1a1a1a",
    margin: "0 0 10px",
    letterSpacing: "-0.02em",
  },

  invalidNoticeText: {
    fontSize: 14,
    color: "#555",
    lineHeight: 1.7,
    margin: "0 0 20px",
    wordBreak: "keep-all",
  },

  invalidNoticeExamples: {
    background: "#fafafa",
    border: "1px solid #eeeeee",
    borderRadius: 10,
    padding: "14px 16px",
    textAlign: "left",
    fontSize: 13,
    color: "#666",
    lineHeight: 1.6,
  },

  invalidNoticeExampleLabel: {
    display: "block",
    fontSize: 12,
    fontWeight: 800,
    color: "#E86F00",
    marginBottom: 6,
  },

  invalidNoticeExampleText: {
    margin: "2px 0",
    fontSize: 13,
    color: "#666",
  },

historyToggleWrapper: {
  marginTop: 18,
},

historyToggleBtn: {
  width: "100%",
  height: 48,
  background: "#fff",
  border: "1px solid #e0e0e0",
  borderRadius: 2,
  padding: "0 16px",
  display: "flex",
  alignItems: "center",
  justifyContent: "space-between",
  fontSize: 14,
  fontWeight: 700,
  color: "#1a1a1a",
  cursor: "pointer",
  fontFamily: "inherit",
},

historyToggleIcon: {
  fontSize: 12,
  color: "#E86F00",
},

historyPanel: {
  marginTop: 8,
  background: "#fff",
  border: "1px solid #e0e0e0",
  borderRadius: 2,
  padding: 16,
},

historyFilterGroup: {
  display: "flex",
  gap: 6,
  justifyContent: "flex-end",
  flexWrap: "wrap",
  marginBottom: 12,
},

historyFilterBtn: {
  padding: "6px 10px",
  fontSize: 12,
  fontWeight: 600,
  color: "#666",
  background: "#f5f5f5",
  border: "1px solid #e0e0e0",
  borderRadius: 20,
  cursor: "pointer",
  fontFamily: "inherit",
},

historyFilterActive: {
  padding: "6px 10px",
  fontSize: 12,
  fontWeight: 700,
  color: "#fff",
  background: "#E86F00",
  border: "1px solid #E86F00",
  borderRadius: 20,
  cursor: "pointer",
  fontFamily: "inherit",
},

historyEmpty: {
  margin: 0,
  fontSize: 13,
  color: "#999",
  textAlign: "center",
  padding: "14px 0",
},

historyList: {
  display: "flex",
  flexDirection: "column",
  gap: 8,
  maxHeight: 220,
  overflowY: "auto",
},

historyItem: {
  width: "100%",
  textAlign: "left",
  background: "#fafafa",
  border: "1px solid #eeeeee",
  borderRadius: 6,
  padding: "10px 12px",
  cursor: "pointer",
  display: "flex",
  flexDirection: "column",
  gap: 4,
  fontFamily: "inherit",
},

historyText: {
  fontSize: 13,
  fontWeight: 600,
  color: "#333",
  lineHeight: 1.5,
},

historyDate: {
  fontSize: 11,
  color: "#999",
},


searchModeRow: {
  maxWidth: 848,
  margin: "0 auto 12px",
  display: "flex",
  alignItems: "stretch",
  gap: 8,
},

searchModeHelpWrap: {
  position: "relative",
  flexShrink: 0,
},

searchModeHelpBtn: {
  width: 25,
  height: 25,
  borderRadius: "50%",
  border: "1px solid #fa8f51",
  background: "#fff",
  color: "#fa8f51",
  fontSize: 13,
  fontWeight: 750,
  cursor: "pointer",
  fontFamily: "inherit",
  boxShadow: "0 4px 10px rgba(0,0,0,0.06)",
  marginTop : 13,
  marginLeft : 3
},

searchModeHelpTooltip: {
  position: "absolute",
  top: 38,
  left: 0,
  width: 350,
  padding: "14px 15px",
  background: "#1f1f1f",
  color: "#fff",
  borderRadius: 12,
  boxShadow: "0 14px 30px rgba(0,0,0,0.20)",
  zIndex: 30,
  boxSizing: "border-box",
},

searchModeHelpTitle: {
  margin: "0 0 10px",
  fontSize: 13,
  fontWeight: 900,
  color: "#fff",
},

searchModeHelpItem: {
  padding: "0 0 10px",
  marginBottom: 10,
  borderBottom: "1px solid rgba(255,255,255,0.12)",
},

searchModeHelpItemLast: {
  padding: 0,
  margin: 0,
},

searchModeHelpBadge: {
  display: "inline-flex",
  alignItems: "center",
  height: 22,
  padding: "0 8px",
  marginBottom: 6,
  borderRadius: 999,
  background: "rgba(232,111,0,0.16)",
  color: "#FFB16A",
  fontSize: 11,
  fontWeight: 900,
},

searchModeHelpText: {
  margin: 0,
  fontSize: 12,
  lineHeight: 1.6,
  color: "#e5e5e5",
},

searchModeBox: {
  flex: 1,
  minWidth: 0,
  display: "flex",
  justifyContent: "center",
  gap: 8,
  background: "#f6f6f6",
  border: "1px solid #eeeeee",
  borderRadius: 14,
  padding: 6,
},

searchModeBtn: {
  flex: 1,
  padding: "9px 12px",
  border: "1px solid transparent",
  borderRadius: 10,
  background: "transparent",
  color: "#777",
  fontSize: 13,
  fontWeight: 700,
  cursor: "pointer",
  fontFamily: "inherit",
  transition: "all 0.18s ease",
},

searchModeBtnActive: {
  flex: 1,
  padding: "9px 12px",
  border: "1px solid #E86F00",
  borderRadius: 10,
  background: "#fff",
  color: "#E86F00",
  fontSize: 13,
  fontWeight: 900,
  cursor: "pointer",
  fontFamily: "inherit",
  boxShadow: "0 6px 16px rgba(232,111,0,0.12)",
  transition: "all 0.18s ease",
},

queryHistoryDropdown: {
  background: "#fff",
  border: "1px solid #e0e0e0",
  borderRadius: 8,
  boxShadow: "0 4px 12px rgba(0,0,0,0.1)",
  maxHeight: 160,
  maxWidth: 848,
  margin: "4px auto 0",
  overflowY: "auto",
},

queryHistoryDropdownItem: {
  width: "100%",
  textAlign: "left",
  padding: "10px 12px",
  background: "#fff",
  border: "none",
  borderBottom: "1px solid #f0f0f0",
  cursor: "pointer",
  fontFamily: "inherit",
  display: "grid",
  gridTemplateColumns: "1fr auto 26px",
  alignItems: "center",
  gap: 10,
},

queryHistoryDropdownText: {
  minWidth: 5,
  overflow: "hidden",
  textOverflow: "ellipsis",
  whiteSpace: "nowrap",
  fontSize: 13,
  color: "#444",
},

queryHistoryDropdownDate: {
  fontSize: 11,
  color: "#aaa",
  whiteSpace: "nowrap",
},


queryHistoryDeleteBtn: {
  width: 22,
  height: 22,
  marginLeft: 0,
  border: "none",
  borderRadius: "50%",
  background: "transparent",
  color: "#b8b8b8",
  fontSize: 12,
  fontWeight: 800,
  lineHeight: "22px",
  textAlign: "center",
  cursor: "pointer",
  flexShrink: 0,
},

searchExampleBar: {
  maxWidth: 848,
  margin: "0 auto",
  borderTop: "1px solid #e0e0e0",
  display: "flex",
  alignItems: "center",
  gap: 8,
  padding: "10px 16px",
  background: "#fff",
  overflow: "hidden",
},

searchExampleLabel: {
  fontSize: 12,
  fontWeight : 700,
  color: "#E86F00",
  flexShrink: 0,
},

searchExampleText: {
  margin: 0,
  fontSize: 13,
  color: "#777",
  animation: "fadeInOut 4.0s ease-in-out",
  overflow: "hidden",
  textOverflow: "ellipsis",
  whiteSpace: "nowrap",
},

caseModePanel: {
  maxWidth: 848,
  margin: "0 auto",
  background: "#fff",
  border: "1px solid #eeeeee",
  borderRadius: 14,
  padding: 18,
  boxSizing: "border-box",
  boxShadow: "0 8px 22px rgba(0,0,0,0.04)",
},

searchExampleBoxSeparate: {
  width: "100%",
  marginTop: 10,
  border: "1px solid #e8e8e8",
  borderRadius: 10,
  display: "flex",
  alignItems: "center",
  gap: 8,
  padding: "9px 12px",
  background: "#fafafa",
  overflow: "hidden",
  boxSizing: "border-box",
},

applyModePanel: {
  maxWidth: 848,
  minHeight: 286,
  margin: "0 auto",
  background: "#fff",
  border: "1px solid #eeeeee",
  borderRadius: 14,
  padding: 16,
  boxSizing: "border-box",
  boxShadow: "0 8px 22px rgba(0,0,0,0.04)",
},

applyModeHeader: {
  marginBottom: 10,
},

applyModeTitle: {
  margin: "0 0 5px",
  fontSize: 15,
  fontWeight: 900,
  color: "#1a1a1a",
},

applyModeDesc: {
  margin: 0,
  fontSize: 13,
  lineHeight: 1.6,
  color: "#777",
},

applyInputGrid: {
  display: "grid",
  gridTemplateColumns: "1fr",
  gap: 9,
},

applyFieldWrap: {
  position: "relative",
  width: "100%",
},

applyFieldWrapWide: {
  position: "relative",
  width: "100%",
},

applyField: {
  position: "relative",
  display: "flex",
  flexDirection: "column",
  gap: 5,
  fontFamily: "inherit",
},

applyFieldWide: {
  position: "relative",
  display: "flex",
  flexDirection: "column",
  gap: 5,
  fontFamily: "inherit",
},

applyFieldLabel: {
  fontSize: 12,
  fontWeight: 850,
  color: "#E86F00",
},

applyInput: {
  width: "100%",
  boxSizing: "border-box",
  border: "1px solid #e6e6e6",
  borderRadius: 10,
  padding: "10px 12px",
  fontSize: 13,
  lineHeight: 1.45,
  color: "#333",
  background: "#fafafa",
  outline: "none",
  fontFamily: "inherit",
},

applyTextarea: {
  width: "100%",
  minHeight: 54,
  resize: "vertical",
  boxSizing: "border-box",
  border: "1px solid #e6e6e6",
  borderRadius: 10,
  padding: "10px 12px",
  fontSize: 13,
  lineHeight: 1.45,
  color: "#333",
  background: "#fafafa",
  outline: "none",
  fontFamily: "inherit",
},

applyTextareaSmall: {
  width: "100%",
  minHeight: 54,
  resize: "vertical",
  boxSizing: "border-box",
  border: "1px solid #e6e6e6",
  borderRadius: 10,
  padding: "10px 12px",
  fontSize: 13,
  lineHeight: 1.45,
  color: "#333",
  background: "#fafafa",
  outline: "none",
  fontFamily: "inherit",
},

applyFieldHistoryDropdown: {
  position: "absolute",
  left: 0,
  right: 0,
  top: "100%",
  zIndex: 30,
  background: "#fff",
  border: "1px solid #e0e0e0",
  borderRadius: 8,
  boxShadow: "0 4px 12px rgba(0,0,0,0.1)",
  maxHeight: 160,
  marginTop: 4,
  overflowY: "auto",
},

applyFieldHistoryItem: {
  width: "100%",
  textAlign: "left",
  padding: "10px 12px",
  background: "#fff",
  border: "none",
  borderBottom: "1px solid #f0f0f0",
  cursor: "pointer",
  fontFamily: "inherit",
  display: "grid",
  gridTemplateColumns: "1fr auto 26px",
  alignItems: "center",
  gap: 10,
  boxSizing: "border-box",
},

applyFieldHistoryText: {
  minWidth: 5,
  overflow: "hidden",
  textOverflow: "ellipsis",
  whiteSpace: "nowrap",
  fontSize: 13,
  color: "#444",
},

applyFieldHistoryDate: {
  fontSize: 11,
  color: "#aaa",
  whiteSpace: "nowrap",
},

applyFieldHistoryDeleteBtn: {
  width: 22,
  height: 22,
  marginLeft: 0,
  border: "none",
  borderRadius: "50%",
  background: "transparent",
  color: "#b8b8b8",
  fontSize: 12,
  fontWeight: 800,
  lineHeight: "22px",
  textAlign: "center",
  cursor: "pointer",
  flexShrink: 0,
},

applyHistoryBox: {
  marginTop: 12,
  border: "1px solid #eeeeee",
  borderRadius: 12,
  background: "#fafafa",
  padding: "10px 12px",
},

applyHistoryHeader: {
  display: "flex",
  alignItems: "center",
  justifyContent: "space-between",
  marginBottom: 8,
},

applyHistoryTitle: {
  fontSize: 12,
  fontWeight: 850,
  color: "#E86F00",
},

applyHistoryList: {
  display: "flex",
  flexDirection: "column",
  gap: 6,
},

applyHistoryItem: {
  width: "100%",
  display: "grid",
  gridTemplateColumns: "1fr auto 24px",
  alignItems: "center",
  gap: 8,
  border: "1px solid #eeeeee",
  borderRadius: 10,
  background: "#fff",
  padding: "8px 10px",
  textAlign: "left",
  cursor: "pointer",
  fontFamily: "inherit",
},

applyHistoryText: {
  minWidth: 0,
  overflow: "hidden",
  textOverflow: "ellipsis",
  whiteSpace: "nowrap",
  fontSize: 12.5,
  color: "#555",
},

applyHistoryDate: {
  fontSize: 11,
  color: "#aaa",
  whiteSpace: "nowrap",
},

applyHistoryDeleteBtn: {
  width: 22,
  height: 22,
  border: "none",
  borderRadius: "50%",
  background: "transparent",
  color: "#b8b8b8",
  fontSize: 12,
  fontWeight: 800,
  lineHeight: "22px",
  textAlign: "center",
  cursor: "pointer",
},
};
